### ISSUE TITLE
Calling Zigzag function with wrong parameters?

### ISSUE THREAD

**Issue by marti1999** [mVirtuoso21/JPEG-Image-Compressor#1]
Hi there, 
I was using you code for a college assignment and I think I might have found bug.
On main.py line 116 and 122 you are using yq as a parameter for the zigzag function. Shouldn't it be crq and cbt?
Additionally, on main.py line 152 you are getting the values from crEncoded, but I think you probably want to get them rom cbEncoded.

Anyway, hope it helps and thanks for this script.

**Comment by mVirtuoso21** [comment]
@marti1999 Hey mate, thanks a lot for pointing that out. Actually, this was one of my projects in college too. I think while trying to used the same code (since all channels use the same formula), I forgot to change the parameters. My apologies.

**Comment by Morwinthren** [comment]
> @marti1999 Hey mate, thanks a lot for pointing that out. Actually, this was one of my projects in college too. I think while trying to use the same code (since all channels use the same formula), I forgot to change the parameters. My apologies.

Do you have a decompression code for this? I'm struggling to decompress this. Thank you so much
