### ISSUE TITLE
Possible Bug in Aggregating ZigZag scanned Blocks

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [mVirtuoso21/JPEG-Image-Compressor#3]
Thanks for the work! I have a question regarding the aggregation step of the zigzag scanned blocks. I'm not entirely sure, but for [line 104](https://github.com/mVirtuoso21/JPEG-Image-Compressor/blob/d4b98179b65a3e73023137279ca500e282e57e56/main.py#L104), [line 115] (https://github.com/mVirtuoso21/JPEG-Image-Compressor/blob/d4b98179b65a3e73023137279ca500e282e57e56/main.py#L115) and [line 121](https://github.com/mVirtuoso21/JPEG-Image-Compressor/blob/d4b98179b65a3e73023137279ca500e282e57e56/main.py#L121) in the `main.py` file, shouldn't the indexing be `i * vBlocksForY + j` and `i * vBlocksForC + j` instead of `i * j`? It seems that when you do `i * j`, the result of many zigzag scanned blocks get added to the same index (let's say 0, because `i * j` when looped gives many 0s). Could you please clarify this soon, thanks!

**Comment by mVirtuoso21** [comment]
@Ashwin-Ramesh2607 thanks a lot for pointing that out. My apologies for the late reply. What you are saying makes perfect sense. When I wrote the code, I thought `i * j` would always produce the number of the next element. However, your solution still has results that overlap. Say `i = 1`, `j = 7` and `vBlocksForY = 5`, then `yZigzag[i * vBlocksForY + j]` becomes `yZigzag[12]`, same if `i = 2` and `j = 2`, then `yZigzag[i * vBlocksForY + j]` becomes `yZigzag[12]`. 
I'm going to introduce a counter for the **y** channel (`yCounter`) and another for the **c** channels (`cCounter`). This way there won't be any overlapping. Thanks a lot and you're welcome to point any further bugs you might find.
